stages:
    - test
    - build

unit-test:
    stage: test
    image: node:22
    script:
        - npm install
        - npm run test:unit

build:
    stage: build
    image: debian
    script:
        - echo 'Job de build'