services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: articles_db
      POSTGRES_USER: articles_user
      POSTGRES_PASSWORD: articles_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U articles_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  pythonx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://articles_user:articles_password@db:5432/articles_db
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=articles_db
      - DB_USER=articles_user
      - DB_PASSWORD=articles_password
    ports:
      - "8000:8000"
    depends_on:
      db: 
        condition: service_healthy
volumes:
  db_data:
