name: CI backend
on: 
    push:
        branches:
        - main
    pull_request:
        # paths:
        # - 'backend/**'

defaults:
  run:
    working-directory: ./backend

env:
    FORCE_COLOR: 3
    CI: true

jobs:
  quality-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install dependencies
        run: uv pip install --system -r requirements/dev.txt

      - name: Check formatting
        run: ruff check

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: setup python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Install dependencies
        run: uv pip install --system -r requirements/requirements.txt

      - name: Setup database
        run: docker compose -f docker-compose.yml up -d

      - name: Setup migrations & load data
        run: |
          uv python manage.py migrate
          uv python manage.py loaddata --format json ./fixtures/dev-fixtures.json
      
      - name: Run tests
        run: uv python manage.py test
