name: CI Frontend
on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - 'frontend/**'

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    working-directory: ./frontend

env:
  FORCE_COLOR: 3
  CI: true
  NODE_VERSION: 22

jobs:
  quality-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Check formatting
      run: npm run format

    - name: Check linting
      run: npm run lint

  test-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test:unit

    - name: Run build
      run: npm run build
