name: CI Frontend
on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - 'frontend/**'
    - '**/ci-front.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read
  pull-requests: read

defaults:
  run:
    shell: bash
    working-directory: ./frontend

env:
  FORCE_COLOR: 1
  CI: true
  NODE_VERSION: 22

jobs:
  quality-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Check formatting
      run: node --run format

    - name: Check linting
      run: node --run lint

  test-front:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: node --run test:unit

    - name: Run build
      run: node --run build
